'use strict';
document.querySelectorAll('.nav-group').forEach(group=>group.addEventListener('toggle',()=>{if(group.open)document.querySelectorAll('.nav-group').forEach(other=>{if(other!==group)other.open=false;});}));
document.addEventListener('click',e=>{if(!e.target.closest('.site-header'))document.querySelectorAll('.site-header details[open]').forEach(d=>d.open=false);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){const open=[...document.querySelectorAll('.site-header details[open]')];if(open.length){const top=open.find(d=>d.contains(document.activeElement))||open[0];open.forEach(d=>d.open=false);top.querySelector('summary').focus();}}});
function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();URL.revokeObjectURL(url);}
function values(form){let valid=true;const data={};for(const el of form.elements){if(!el.name)continue;el.setCustomValidity('');const v=el.value.trim();if(el.required&&!v){el.setCustomValidity('请填写有效内容。');valid=false;}data[el.name]=v;}if(!valid)form.reportValidity();return valid?data:null;}
document.querySelectorAll('input,textarea').forEach(el=>el.addEventListener('input',()=>el.setCustomValidity('')));
const brief=document.querySelector('#brief-form');
if(brief){let result='';const copy=document.querySelector('#brief-copy'),save=document.querySelector('#brief-download'),status=document.querySelector('#brief-status');brief.addEventListener('submit',e=>{e.preventDefault();const v=values(brief);if(!v)return;result='# '+v.name+'\n\n## 目标与受众\n'+v.goal+'\n\n## 交付形式\n'+v.format+'\n\n## 约束与完成标准\n'+v.constraints+'\n\n## 开始前确认\n- [ ] 目标与受众明确\n- [ ] 输入材料与来源齐全\n- [ ] 完成标准可以检查\n- [ ] 工具使用与授权范围已确认\n';document.querySelector('#brief-result').textContent=result;copy.disabled=false;save.disabled=false;status.textContent='简报已生成，内容仅在当前页面中。';});document.querySelector('#brief-example').addEventListener('click',()=>{brief.elements.name.value='社区月刊 · 第一次 AI 创作';brief.elements.goal.value='为第一次接触 AI 创作的读者介绍三个可以尝试的方法，帮助他们完成一次小实验。';brief.elements.constraints.value='包含目录、三项实验与参考链接。每项实验说明输入、步骤、结果和限制。手机上可以完整阅读；邀请一名新读者按步骤完成实验。';});copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(result);status.textContent='简报已复制。';}catch{status.textContent='浏览器未允许复制，请使用“下载 Markdown”。';}});save.addEventListener('click',()=>{download(result,'entelina-brief.md');status.textContent='简报文件已准备下载。';});}
const indexForm=document.querySelector('#index-form');
if(indexForm){let result='';indexForm.addEventListener('submit',e=>{e.preventDefault();const v=values(indexForm);if(!v)return;const source=indexForm.elements.source.value;const lines=source.split(/\r?\n/),items=[];let fence=null,jumps=0,last=0;lines.forEach((line,i)=>{const f=line.match(/^ {0,3}(\u0060{3,}|~{3,})(.*)$/);if(f){if(!fence){if(f[1][0]!=='\u0060'||!f[2].includes('\u0060'))fence={char:f[1][0],length:f[1].length};}else if(f[1][0]===fence.char&&f[1].length>=fence.length&&!f[2].trim())fence=null;return;}if(fence)return;const match=line.match(/^ {0,3}(#{1,6})(?:[ \t]+(.*)|$)/);if(match){const level=match[1].length,title=(match[2]||'').replace(/[ \t]+#+[ \t]*$/,'').trim()||'（空标题）';if(last&&level>last+1)jumps++;last=level;items.push({level,title,line:i+1});}});const ol=document.querySelector('#index-outline');ol.replaceChildren();for(const item of items){const li=document.createElement('li');li.textContent='H'+item.level+' · '+item.title+' — 第 '+item.line+' 行';li.style.marginLeft=Math.min(item.level-1,3)*10+'px';ol.append(li);}document.querySelector('#index-stats').textContent=items.length+' 个标题 · '+lines.length+' 行 · '+source.length+' 个字符';document.querySelector('#index-hint').textContent=!items.length?'没有找到 # 标题。请使用 # 加空格开头的 Markdown 标题。':jumps?'发现 '+jumps+' 处标题层级跨越，请结合内容判断是否需要调整。':'标题层级没有跨越提醒。请继续检查内容与顺序是否符合阅读目标。';result='# 文档结构索引\n\n'+items.map(x=>'  '.repeat(x.level-1)+'- '+x.title+'（H'+x.level+'，第 '+x.line+' 行）').join('\n');document.querySelector('#index-download').disabled=!items.length;document.querySelector('#index-status').textContent='分析完成；没有上传文档。';});document.querySelector('#index-example').addEventListener('click',()=>indexForm.elements.source.value='# 项目说明\n\n## 为什么做这个工具\n说明要解决的问题。\n\n## 开始使用\n### 输入与输出\n填写必要内容。\n\n## 已知限制\n记录当前能力边界。\n\n## 后续计划\n写下值得继续验证的问题。');document.querySelector('#index-download').addEventListener('click',()=>{download(result,'entelina-index.md');document.querySelector('#index-status').textContent='索引文件已准备下载。';});}
const proposal=document.querySelector('#proposal-form');
if(proposal){let result='';const type=new URLSearchParams(location.search).get('type');if([...proposal.elements.type.options].some(o=>o.value===type))proposal.elements.type.value=type;proposal.addEventListener('submit',e=>{e.preventDefault();const v=values(proposal);if(!v)return;result='# '+v.title+'\n\n提案类型：'+v.type+'\n\n## 问题或主题\n'+v.problem+'\n\n## 现有成果与需要的帮助\n'+v.plan+'\n\n## 来源、工具与授权\n'+v.credits+'\n\n---\n本文件由 Entelina 本地提案工具整理，尚未提交。\n';document.querySelector('#proposal-result').textContent=result;document.querySelector('#proposal-download').disabled=false;document.querySelector('#proposal-status').textContent='提案已生成，尚未提交给任何人。';});document.querySelector('#proposal-download').addEventListener('click',()=>{download(result,'entelina-proposal.md');document.querySelector('#proposal-status').textContent='提案已准备下载。此操作不会提交提案。';});}
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));let count=0;document.querySelectorAll('[data-kind]').forEach(x=>{x.hidden=b.dataset.filter!=='all'&&x.dataset.kind!==b.dataset.filter;if(!x.hidden)count++;});document.querySelector('#filter-count').textContent=count+' 件作品';}));
const search=document.querySelector('#site-search');
if(search){const groups={products:'产品',resources:'资源',showcase:'作品',community:'社区',about:'关于',home:'首页'};search.addEventListener('input',()=>{const q=search.value.trim().toLowerCase(),target=document.querySelector('#search-results');target.replaceChildren();if(!q){document.querySelector('#search-count').textContent='输入关键词，搜索全站内容。';return;}const terms=q.split(/\s+/);const found=(window.ENTELINA_PAGES||[]).filter(p=>terms.every(t=>(p.title+' '+p.description+' '+p.text).toLowerCase().includes(t))).sort((a,b)=>Number(b.title.toLowerCase().includes(q))-Number(a.title.toLowerCase().includes(q)));document.querySelector('#search-count').textContent=found.length?'找到 '+found.length+' 个页面':'没有匹配内容。试试更短的关键词，例如“文档”或“Brief”。';for(const item of found){const a=document.createElement('a');a.className='list-row';a.href=item.url;const meta=document.createElement('span');meta.className='meta';meta.textContent=groups[item.group]||'页面';const content=document.createElement('div'),title=document.createElement('h3'),desc=document.createElement('p'),arrow=document.createElement('span');title.textContent=item.title;desc.textContent=item.description;arrow.textContent='↗';arrow.setAttribute('aria-hidden','true');content.append(title,desc);a.append(meta,content,arrow);target.append(a);}});}
