const fs=require('fs'),path=require('path');const root=__dirname,pages=[];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const groups={
products:[['产品总览','products.html','本地工具与项目'],['Brief','product-brief.html','结构化创作简报'],['Index','product-index.html','Markdown 阅读结构'],['产品提案','contribute.html','从提案到持续维护']],
resources:[['资源中心','resources.html','所有知识入口'],['文档','docs.html','开始使用与发布'],['Entelina 用例','use-cases.html','从任务出发'],['更新日志','changelog.html','记录每一次变化'],['实用手册','handbook.html','可以照着做的方法'],['开发者案例','developer-showcase.html','看见实现过程'],['开发者博客','developer-blog.html','工程与设计思考'],['开发者入口','developers.html','开始构建']],
community:[['社区总览','community.html','找到你的参与方式'],['共创提案','contribute.html','准备一份项目提案'],['发布与交流规范','guidelines.html','清楚署名，具体交流'],['发展路线','roadmap.html','接下来的建设方向']],
about:[['关于 Entelina','about.html','我们的立场与方向'],['品牌资产','brand.html','标志、色彩与下载'],['隐私与本地数据','privacy.html','你的内容如何处理']]};
const links=g=>groups[g].map(([t,u,d])=>'<a href="'+u+'">'+t+'<span>'+d+'</span></a>').join('');
function nav(p){const drop=(g,t,desc)=>'<details class="nav-group"><summary data-active="'+(p.group===g)+'">'+t+'</summary><div class="mega"><div class="wrap mega-inner"><div class="mega-lead"><strong>'+t+'</strong><p>'+desc+'</p></div><div class="mega-links">'+links(g)+'</div></div></div></details>';return '<a class="skip" href="#main">跳至正文</a><header class="site-header"><div class="wrap header-inner"><a class="brand" href="index.html" aria-label="Entelina 首页"><img src="logo-ink.svg" alt="" width="34" height="34"><span class="brand-name">Entelina</span></a><nav class="desktop-nav" aria-label="主导航">'+drop('products','产品','把具体的问题，做成可以使用的工具。')+'<a href="showcase.html"'+(p.group==='showcase'?' aria-current="page"':'')+'>作品</a>'+drop('resources','资源','从第一次尝试，到持续深入。')+drop('community','社区','一个正在筹备的共创社区。')+drop('about','关于','长期的创造，始于共同的信念。')+'</nav><div class="header-actions"><a href="search.html" class="search-link" aria-label="搜索全站"><span class="search-icon" aria-hidden="true"></span><span class="search-label">搜索</span></a><a href="community.html" class="button">参与共创</a></div><details class="mobile-nav"><summary aria-label="打开导航菜单">菜单</summary><nav class="mobile-panel" aria-label="移动导航"><a href="index.html">首页</a><details><summary>产品</summary>'+links('products')+'</details><a href="showcase.html">作品展示</a><details><summary>资源</summary>'+links('resources')+'</details><details><summary>社区</summary>'+links('community')+'</details><details><summary>关于</summary>'+links('about')+'</details><a href="search.html">搜索全站</a></nav></details></div></header>';}
function footer(){return '<footer class="site-footer"><div class="wrap"><div class="footer-top"><div class="footer-intro"><a class="footer-brand" href="index.html">Entelina</a><p>连接研究、开发与创作。<br>让智慧成为共同的创造。</p></div>'+[['产品',groups.products.slice(0,3)],['资源',groups.resources.slice(1)],['社区',groups.community],['关于',groups.about]].map(([t,items])=>'<div class="footer-col"><strong>'+t+'</strong>'+items.map(([t,u])=>'<a href="'+u+'">'+t+'</a>').join('')+'</div>').join('')+'</div><div class="footer-bottom"><span>© 2026 Entelina · 来希</span><span><a href="privacy.html">隐私与本地数据</a>　 /　 <a href="sitemap.html">网站地图</a>　 /　 中文</span></div></div></footer>'}
function add(file,title,group,description,body){pages.push({file,title,group,description,body})}
const button=(t,u,s=false)=>'<a class="button'+(s?' secondary':'')+'" href="'+u+'">'+t+'<span aria-hidden="true">↗</span></a>';
const link=(t,u)=>'<a class="text-link" href="'+u+'">'+t+'<span aria-hidden="true">↗</span></a>';
const head=(e,t,d,x='')=>'<div class="wrap page-head"><p class="eyebrow">'+e+'</p><h1>'+t+'</h1><p class="lead">'+d+'</p>'+x+'</div>';
const sh=(e,t,d,l='')=>'<div class="section-head"><div><p class="eyebrow">'+e+'</p><h2>'+t+'</h2>'+(d?'<p>'+d+'</p>':'')+'</div>'+l+'</div>';
const row=(tag,t,d,u)=>'<a class="list-row" href="'+u+'"><span class="meta">'+tag+'</span><div><h3>'+t+'</h3><p>'+d+'</p></div><span aria-hidden="true">↗</span></a>';
const card=(tag,t,d,u)=>'<a class="card" href="'+u+'"><span class="eyebrow">'+tag+'</span><h3>'+t+'</h3><p>'+d+'</p><span class="card-bottom">继续探索 <span aria-hidden="true">↗</span></span></a>';
const productCard=(name,sub,d,u,dark=false)=>'<a class="card product-card" href="'+u+'"><div class="product-face'+(dark?' dark':'')+'"><span>ENTELINA / '+name.toUpperCase()+'</span><strong>'+name+'</strong><span>'+sub+'</span></div><div class="card-copy"><h3>'+name+'</h3><p>'+d+'</p><span class="card-bottom"><span>本地工具 · v0.1</span><span>打开工具 ↗</span></span></div></a>';
const productCards=()=>productCard('Brief','DEFINE BEFORE YOU CREATE','把目标、受众与约束整理成一份可执行的创作简报。','product-brief.html',true)+productCard('Index','A CLEARER WAY TO READ','从 Markdown 中提取标题层级，让长文档的结构一目了然。','product-index.html');
const tabs=current=>'<nav class="tabs" aria-label="资源分类">'+groups.resources.slice(0,7).map(([t,u])=>'<a href="'+u+'"'+(current===u?' aria-current="page"':'')+'>'+t+'</a>').join('')+'</nav>';
function article(file,title,group,kicker,desc,sections,related=[],extra=''){add(file,title,group,desc,head(kicker,title,desc,'<div class="article-meta"><span>Entelina 编辑与开发记录</span><span>2026.09.13</span><span>初版</span></div>')+'<div class="wrap article-layout"><aside class="article-sidebar" aria-label="文章目录"><strong>本页内容</strong>'+sections.map(([t],i)=>'<a href="#section-'+(i+1)+'">'+t+'</a>').join('')+'</aside><article class="article-body">'+extra+sections.map(([t,b],i)=>'<section><h2 id="section-'+(i+1)+'">'+t+'</h2>'+b+'</section>').join('')+(related.length?'<div class="related"><strong>继续探索</strong>'+related.map(([t,u])=>'<a href="'+u+'">'+t+' ↗</a>').join('')+'</div>':'')+'</article></div>')}
const p=t=>'<p>'+t+'</p>',ul=items=>'<ul>'+items.map(t=>'<li>'+t+'</li>').join('')+'</ul>';
const api={add,head,sh,link,button,row,card,productCards,tabs,article,p,ul};
require('./pages-main.cjs')(api);require('./pages-tools.cjs')(api);require('./content.cjs')(api);
add('sitemap.html','网站地图','about','Entelina 所有页面的快捷入口。',head('SITE DIRECTORY','每一条路径，都清楚可达。','从这里进入 Entelina 的全部页面。')+'<div class="wrap page-content site-map">'+pages.filter(p=>p.file!=='404.html').map(p=>'<a href="'+p.file+'">'+p.title+' ↗</a>').join('')+'</div>');
for(const page of pages){const crumb=page.file==='index.html'?'':'<div class="wrap crumbs"><a href="index.html">首页</a><span>/</span><span>'+esc(page.title)+'</span></div>';fs.writeFileSync(path.join(root,page.file),'<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(page.title)+' — Entelina 来希</title><meta name="description" content="'+esc(page.description)+'"><meta name="theme-color" content="#173c34"><link rel="icon" href="assets/favicon.svg?v=3" type="image/svg+xml"><link rel="icon" href="assets/favicon-32.png?v=3" sizes="32x32" type="image/png"><link rel="apple-touch-icon" href="assets/apple-touch-icon.png?v=3"><link rel="stylesheet" href="styles.css"></head><body>'+nav(page)+'<noscript><div class="no-js">页面与导航可以正常阅读；本地工具和搜索需要启用 JavaScript。</div></noscript><main id="main">'+crumb+page.body+'</main>'+footer()+'<script src="search-index.js"></script><script src="app.js"></script></body></html>');}
fs.writeFileSync(path.join(root,'search-index.js'),'window.ENTELINA_PAGES='+JSON.stringify(pages.filter(p=>!['404.html','search.html'].includes(p.file)).map(p=>({title:p.title,url:p.file,group:p.group,description:p.description,text:p.body.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').slice(0,6000)})))+';');
fs.writeFileSync(path.join(root,'pages.json'),JSON.stringify(pages.map(({file,title,group})=>({file,title,group})),null,2));console.log('Built '+pages.length+' HTML pages.');
