module.exports=({add,head,sh,link,button,row,card,productCards,tabs})=>{
const wrap=t=>'<div class="wrap page-content">'+t+'</div>',section=t=>'<section class="section"><div class="wrap">'+t+'</div></section>';
add('index.html','共同探索，持续创造','home','Entelina 连接研究、开发与创作，让个人灵感成为可以使用、学习与延续的共同成果。',
'<section class="wrap hero"><div class="hero-main"><div><p class="eyebrow">A COMMUNITY FOR HUMAN × AI</p><h1>共同探索。<br>持续创造。</h1><p class="hero-line">Intelligence, made collective.</p><p class="lead">一个正在筹备的 AI 共创社区。<br>已经做出两款可以立刻使用的本地工具。</p><div class="action-row">'+button('查看本地工具','products.html')+link('阅读作品样刊','showcase.html')+'</div></div><figure class="hero-image"><img src="assets/unfolding.webp" alt="深墨绿空间中向外展开的手工纸花瓣雕塑" width="1536" height="1024"><figcaption><span>ENTELINA / THE UNFOLDING</span><span>展开，是创造的起点。</span></figcaption></figure></div><div class="hero-footer"><a href="products.html"><span>使用 · 本地工具</span><span>↗</span></a><a href="showcase.html"><span>观看 · 创作与过程</span><span>↗</span></a><a href="resources.html"><span>学习 · 可延续的知识</span><span>↗</span></a></div></section>'+
section(sh('LOCAL TOOLS','从一个问题，到一件产品。','让好的方法走出个人工作流，成为可以使用的工具。',link('全部产品','products.html'))+'<div class="grid two">'+productCards()+'</div>')+
'<section class="section dark-section"><div class="wrap feature-split"><div><p class="eyebrow">ENTELINA SELECTED / ISSUE 000</p><h2>作品之外，<br>还有值得分享的过程。</h2><p>从一张纸的形态，到一个品牌的秩序。<br>在第 000 期样刊里，了解 Entelina 的第一组创作实验。</p><div class="action-row">'+button('阅读本期样刊','issue-000.html')+'</div></div><img src="assets/unfolding.webp" alt="第 000 期样刊：展开" width="1536" height="1024"></div></section>'+
section(sh('KNOWLEDGE, SHARED','经验值得被留下。','文档、实践与工程思考，连接不同阶段的探索。',link('进入资源中心','resources.html'))+'<div class="row-list">'+row('文档 / 入门','第一次来到 Entelina','找到工具、阅读作品，或准备你的第一份共创提案。','docs-start.html')+row('用例 / 创作','用 Brief 把想法变成创作任务','从模糊愿望开始，写清楚受众、交付物与判断标准。','case-brief.html')+row('开发者博客 / 工程','先让工具在本地成立','讨论本地工具的边界，以及可以逐步扩展的产品基础。','blog-local.html')+'</div>')+
section('<div class="split-content"><h2>不同的专长，<br>共同的创造。</h2><div><p>你可以编写代码、设计体验、整理知识，也可以提出一个更好的问题。Entelina 正在为这些不同的贡献准备入口。</p>'+button('找到参与方式','community.html')+'</div></div>'));
add('products.html','产品','products','Entelina 现有的两款本地工具，以及它们解决的问题与边界。',head('PRODUCTS / LOCAL TOOLS','把想法，做成工具。','两款在浏览器本地运行的工具，处理创作简报与文档结构。它们不调用模型，也不上传输入。')+wrap('<div class="tabs"><a aria-current="page" href="products.html">所有产品</a><a href="contribute.html">准备产品提案</a><a href="docs-products.html">产品文档</a></div><div class="grid two">'+productCards()+'</div><div class="notice">当前提供两款无需账号的本地工具。它们帮助组织 AI 工作流，不调用模型，也不会上传输入内容。</div>')+section(sh('HOW A TOOL GETS MADE','下一个工具，可以从你开始。','先解决一个真实问题，再邀请不同专长的人一起完善。')+'<div class="step-grid">'+[['01','定义问题','写清楚谁遇到什么困难，以及现有做法哪里不够好。'],['02','做出原型','用最小的可运行版本，让想法可以被体验。'],['03','共同评审','分享限制、测试方法与实现过程，收集具体反馈。'],['04','持续维护','保留版本记录，说明负责人、许可和后续计划。']].map(([n,t,d])=>'<div class="step"><span class="number">'+n+'</span><h3>'+t+'</h3><p>'+d+'</p></div>').join('')+'</div><div class="action-row">'+button('准备共创提案','contribute.html')+link('阅读发布规范','docs-publishing.html')+'</div>'));
const works=()=>'<a class="image-card" data-kind="visual" href="work-unfolding.html"><figure><img src="assets/unfolding.webp" alt="手工纸花瓣雕塑：展开" width="1536" height="1024"></figure><h3>展开 / The Unfolding</h3><p>以手工纸的展开，研究结构、光线与对称。</p><div class="meta">视觉实验 · 第 000 期样刊 · Entelina 品牌习作</div></a><a class="image-card" data-kind="design" href="work-identity.html"><figure><img src="assets/identity-cover.svg" alt="Entelina 标志与字标" width="900" height="600"></figure><h3>共同的标记 / A Shared Mark</h3><p>一枚八瓣放射的标志，如何成为一套能长期使用的系统。</p><div class="meta">品牌设计 · 第 000 期样刊 · Entelina 品牌习作</div></a>';
add('showcase.html','作品','showcase','按期呈现 Entelina 的作品与创作过程，记录方法、工具和每一次有价值的选择。',head('ENTELINA SELECTED','看见作品，也看见创造。','第 000 期样刊收录 Entelina 自己的两项品牌习作。社区投稿入口尚未开放。')+wrap('<div class="filters"><div aria-label="作品分类"><button class="chip" data-filter="all" aria-pressed="true">全部作品</button><button class="chip" data-filter="visual" aria-pressed="false">视觉实验</button><button class="chip" data-filter="design" aria-pressed="false">品牌设计</button></div><a class="text-link" href="editions.html">期刊归档 ↗</a></div><p class="results-note" id="filter-count" role="status">2 件作品</p><div class="grid two" id="work-grid">'+works()+'</div><div class="notice">第 000 期为网站样刊，收录的是本次品牌设计的真实产物，不代表已开展的社区评选。社区投稿入口尚未开放；正式期刊将按发布规范录入作品与作者信息。</div><div class="backlinks">'+link('作品发布规范','docs-publishing.html')+link('准备作品材料','contribute.html?type=作品展示')+'</div>'));
add('editions.html','期刊归档','showcase','按期归档 Entelina 的作品与创作过程。',head('SELECTED / ARCHIVE','每一期，都是一次新的观看。','按期阅读作品、创作过程与编辑说明。')+wrap('<div class="row-list">'+row('ISSUE 000 / 样刊','展开。','2026.09 · 视觉与品牌 · 2 项 Entelina 品牌习作。','issue-000.html')+'</div><div class="notice">正式期刊将从第 001 期开始。当前仅展示样刊，不预填未发生的历史期次。</div>'));
add('issue-000.html','第 000 期 · 展开','showcase','Entelina 第 000 期样刊，以两项品牌习作展示作品与过程的归档方式。',head('SELECTED / ISSUE 000','展开。','两项品牌习作，记录 Entelina 从一枚标志到一套视觉系统的过程。')+wrap('<div class="edition-cover"><div><p class="eyebrow">THE FIRST FOLIO</p><h2>The<br>Unfolding.</h2><p>第 000 期 · 样刊<br>2026.09 / 视觉与品牌</p></div><img src="assets/unfolding.webp" alt="第 000 期主视觉：手工纸花瓣展开"></div><div class="section-head" style="margin-top:45px"><div><h2>本期内容</h2><p>两项品牌习作，一次关于 Entelina 的初步表达。</p></div></div><div class="grid two">'+works()+'</div><div class="notice">这是上线前样刊。正式期次、作者、评审与发布时间以未来实际发布为准。</div>'));
add('resources.html','资源中心','resources','文档、用例、更新日志、实用手册、开发者案例与博客。',head('ENTELINA RESOURCES','知识，从这里继续。','从第一次使用，到独立完成一个项目。找到与你当前问题有关的知识。')+wrap(tabs('resources.html')+'<div class="grid resource-grid">'+[['01 / DOCUMENTATION','文档','从入门到产品使用，再到作品和产品的发布。','docs.html'],['02 / USE CASES','Entelina 用例','沿着真实任务，理解工具与方法如何组合。','use-cases.html'],['03 / CHANGELOG','Entelina 更新日志','按时间记录官网与本地工具的实际变化。','changelog.html'],['04 / HANDBOOK','实用手册','把提示设计、复盘和协作变成可执行的方法。','handbook.html'],['05 / DEVELOPER SHOWCASE','开发者案例展示','从结构、边界和验证方式理解一个实现。','developer-showcase.html'],['06 / DEVELOPER BLOG','开发者博客','关于本地优先、产品设计与知识沉淀的思考。','developer-blog.html']].map(x=>card(...x)).join('')+'</div>'));
const cats=[
['docs.html','文档','DOCUMENTATION','从这里开始使用 Entelina。','按任务查找说明，了解工具能力与发布要求。',[['入门','第一次来到 Entelina','从工具、作品和资源三个入口开始。','docs-start.html'],['产品','Brief 与 Index 使用说明','输入格式、输出内容，以及工具的边界。','docs-products.html'],['发布','产品与作品发布指南','准备可复现、清楚署名的发布材料。','docs-publishing.html']]],
['use-cases.html','Entelina 用例','USE CASES','让方法，落到具体任务。','用一份可重复的过程，连接问题与产出。',[['创作流程','从想法到创作简报','用 Brief 明确目标、受众与完成标准。','case-brief.html'],['知识整理','为一份长文档建立阅读地图','用 Index 检查层级，整理分享前的文档。','case-reading.html']]],
['handbook.html','实用手册','PRACTICAL HANDBOOK','少一些猜测，多一些方法。','可执行的步骤，帮助你组织下一次创作与协作。',[['提示设计','一份清晰提示的四个部分','任务、上下文、约束与验收标准。','handbook-prompt.html'],['作品复盘','如何给出有用的作品反馈','先描述观察，再解释影响，最后提出建议。','handbook-review.html']]],
['developer-showcase.html','开发者案例展示','DEVELOPER SHOWCASE','把实现过程，也分享出来。','每个案例都说明问题、设计取舍与验证方式。',[['官网实现','一个无构建依赖的多页面官网','共享导航、静态内容与离线可读的结构。','devcase-static.html'],['工具实现','从 Markdown 到结构索引','识别标题、处理代码围栏与组织导出内容。','devcase-markdown.html']]],
['developer-blog.html','开发者博客','ENGINEERING NOTES','关于构建，保持思考。','记录工程判断与产品取舍，让经验可以被讨论。',[['工程 / 2026.09.13','先让工具在本地成立','把问题与边界明确下来，再增加系统复杂度。','blog-local.html'],['设计 / 2026.09.13','AI 产品的秩序感来自哪里','从界面的一致性，到能力的如实表达。','blog-design.html']]]
];for(const[f,t,k,h,d,items]of cats)add(f,t,'resources',d,head(k,h,d)+wrap(tabs(f)+'<div class="row-list">'+items.map(x=>row(...x)).join('')+'</div>'));
add('changelog.html','Entelina 更新日志','resources','记录官网与本地工具的实际更新。',head('CHANGELOG','每一次改变，都留下记录。','产品、内容与网站的变化，在这里按时间归档。')+wrap(tabs('changelog.html')+'<div class="row-list">'+row('2026.09.13 / v0.3','标志与说明修订','换用八瓣放射展开的标志，补齐矢量与头像资产；清理与旧标志绑定的表述；写明工具不调用模型、投稿入口尚未开放。','release-03.html')+row('2026.09.13 / v0.2','多页面官网初版','统一导航；新增产品、作品样刊与六类资源入口；加入 Brief、Index 本地工具；移除全部视觉动态。','release-02.html')+row('2026.09.13 / v0.1','品牌与首页初稿','建立 Entelina 的墨绿视觉方向、主视觉习作与首页构想。','release-01.html')+'</div>'));
add('developers.html','开发者入口','resources','使用本地工具、阅读实现案例，并准备你的项目提案。',head('BUILD WITH ENTELINA','把知识，变成下一步的构建。','从工具和案例出发，理解实现过程，并准备一份提案。')+wrap('<div class="grid">'+card('START','使用与发布文档','了解现有工具能力，以及产品发布需要准备的内容。','docs.html')+card('LEARN','开发者案例','查看官网与 Markdown 工具的实现方式。','developer-showcase.html')+card('CONTRIBUTE','参与共创','先描述一个明确的问题，再组织最小原型。','contribute.html')+'</div><div class="notice">当前没有 Entelina 模型 API、SDK 或开发者密钥服务。现有工具独立运行，不要求注册账号。</div>'));
add('community.html','社区','community','研究者、开发者与创作者的共创入口。',head('THE ENTELINA COMMUNITY','不同的专长。<br>共同的创造。','社区正在筹备中。我们希望以具体问题相遇，以可分享的成果连接；研究、开发、设计与知识整理，都是共创的一部分。')+wrap('<div class="grid">'+card('BUILD','参与产品共创','提出一个值得解决的问题，准备可体验的原型与说明。','contribute.html?type=产品共创')+card('CREATE','分享一件作品','整理作品、工具与关键选择，让创作过程也被看见。','contribute.html?type=作品展示')+card('DOCUMENT','留下有用的方法','把反复有效的做法写成用例、手册或开发者文章。','contribute.html?type=资源文章')+'</div>')+section('<div class="split-content"><h2>先建立信任，<br>再一起走远。</h2><div><p>好的交流始于清楚的来源和具体的反馈。我们鼓励记录过程、承认限制，也鼓励对已有结论提出有依据的不同意见。</p><div class="backlinks">'+link('阅读交流规范','guidelines.html')+link('查看建设路线','roadmap.html')+'</div></div></div>')+section('<div class="faq"><details><summary>我不是开发者，也可以参与吗？</summary><p>可以。设计、写作、测试、整理知识和提出真实问题，都能够帮助一个项目前进。</p></details><details><summary>社区现在是什么状态？</summary><p>正在筹备中。官网与两款本地工具已经可以真实使用；账号、投稿接收与讨论入口尚未开放，也没有承诺的开放时间。</p></details><details><summary>现在如何提交作品或加入社区？</summary><p>官网目前提供本地提案准备工具，可下载材料保存。正式投稿、账号与讨论入口尚未开放，提案不会自动发送。</p></details><details><summary>什么样的工具适合放进这个社区？</summary><p>有明确使用场景、可体验版本与维护计划的工具。可以从小范围做起，但需要如实说明功能、许可和已知限制。</p></details></div>'));
add('about.html','关于 Entelina','about','让研究、开发与创作彼此连接，留下可以共同延续的成果。',head('ABOUT ENTELINA','让智慧，成为共同的创造。','Entelina 是一个正在筹备中的 AI 共创社区，围绕工具、作品与知识展开。我们关心工具能做什么，也关心人们如何一起把它用好。')+wrap('<div class="brand-panel"><img src="logo.svg" alt="Entelina 标志"><span>Entelina</span></div>')+section('<div class="split-content"><h2>有审美，<br>也有方法。</h2><div><p>艺术帮助我们看到新的可能，工程帮助我们把可能变成稳定的体验。知识的记录与分享，让这些经验不止属于一个人。</p><p>Entelina 希望让这三个方向形成循环：从真实问题出发，制作工具与作品，再把过程中学到的东西交回社区。当前社区仍在筹备，现有成果以官网与两款本地工具为主。</p></div></div>')+section('<div class="grid">'+card('01 / OPEN','开放的起点','给不同背景的人明确的参与方式，让问题与过程都有被讨论的空间。','community.html')+card('02 / CARE','认真对待细节','以清楚的来源、可复现的说明和诚实的能力边界建立信任。','guidelines.html')+card('03 / CONTINUITY','留下可延续的成果','通过文档、版本与维护计划，让作品之外的经验继续发生作用。','roadmap.html')+'</div>'));
add('brand.html','品牌资产','about','Entelina 标志、头像、配色与使用规范。',head('BRAND ASSETS','一个共同的标记。','标志由八片尖端朝内的楔形组成，外圈是一道断开的墨绿环带——潜能一圈圈展开，成为现实。全部为平面纯色，不使用渐变、发光或立体效果。')+wrap('<div class="brand-panel"><img src="logo.svg" alt="Entelina 标志"><span>Entelina</span></div><div class="logo-downloads"><a href="logo-avatar.png" download>下载标准头像 PNG</a><a href="logo-ink.svg" download>下载彩色 SVG（浅底用）</a><a href="logo.svg" download>下载反白 SVG（深底用）</a><a href="logo-avatar-light.png" download>下载浅底头像</a></div><div class="section-head" style="margin-top:55px"><div><h2>为不同的界面，保持同一种识别。</h2><p>深墨绿作骨架、纸白作底、琥珀与陶土作暖色，保持充足留白；不使用渐变、投影与动画。</p></div></div><div class="avatar-grid"><figure><img src="logo-avatar.png" alt="墨绿方形头像"><figcaption>标准头像</figcaption></figure><figure><img class="circle" src="logo-avatar.png" alt="圆形裁切头像"><figcaption>圆形裁切</figcaption></figure><figure><img class="circle" src="logo-avatar-light.png" alt="浅底圆形头像"><figcaption>浅色背景</figcaption></figure></div><div class="brand-swatches"><div class="swatch dark">深墨绿<br>#173C34</div><div class="swatch">纸白<br>#F6F6F2</div><div class="swatch amber">琥珀<br>#B4761C</div><div class="swatch clay">陶土<br>#9C4A16</div></div><div class="article-body" style="max-width:800px;margin-top:38px"><h2>使用原则</h2><ul><li>导航和对外介绍优先使用完整 Entelina 字标；头像与小图标使用独立标志。</li><li>浅色底使用彩色版本，深色底使用反白版本。</li><li>保持原始比例，标志周围至少留出其宽度四分之一的空间。</li><li>使用平面纯色版本，不添加渐变、投影、描边、旋转或动画。</li><li>不要让品牌标记暗示未经确认的合作或官方背书。</li></ul></div>'));
add('search.html','搜索','resources','搜索产品、作品、文档与社区内容。',head('SEARCH ENTELINA','找到下一步。','搜索产品、作品、文档与社区内容。')+wrap('<div class="search-box"><label for="site-search" class="eyebrow" style="display:block">关键词</label><input id="site-search" class="search-input" type="search" placeholder="试试：Brief、发布、作品、Markdown" autocomplete="off"><p id="search-count" class="results-note" role="status">输入关键词，搜索全站内容。</p><div id="search-results" class="search-results row-list"></div></div>'));
add('404.html','页面未找到','home','寻找的页面不存在。',head('404 / NOT FOUND','这一页，还没有写下。','链接可能已变更。你可以返回首页，或搜索感兴趣的内容。','<div class="action-row">'+button('返回首页','index.html')+button('搜索全站','search.html',true)+'</div>'));
};
